<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="#">MyCo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/index">Keluar</a>
            </li>
        </ul>
    </div>
</nav>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="pills-pegawai-tab" data-toggle="pill" href="#pills-pegawai" role="tab" aria-controls="pills-pegawai" aria-selected="true">Pegawai</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="pills-tugas-tab" data-toggle="pill" href="#pills-tugas" role="tab" aria-controls="pills-tugas" aria-selected="false">Tugas</a>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-pegawai" role="tabpanel" aria-labelledby="pills-pegawai-tab">...</div>
    <div class="tab-pane fade" id="pills-tugas" role="tabpanel" aria-labelledby="pills-tugas-tab" style="padding-top:50px">
            <div class="row justify-content-center align-items-center">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-tugas">Tambah Tugas</button>
            </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="modal-tugas" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Tugas</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="beranda">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Judul Tugas</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Masukan Judul">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Detail Tugas</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</div>