<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="#">MyCo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/index">Keluar</a>
            </li>
        </ul>
    </div>
</nav>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="pills-pegawai-tab" data-toggle="pill" href="#pills-pegawai" role="tab" aria-controls="pills-pegawai" aria-selected="true">Pegawai</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="pills-tugas-tab" data-toggle="pill" href="#pills-tugas" role="tab" aria-controls="pills-tugas" aria-selected="false">Tugas</a>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-pegawai" role="tabpanel" aria-labelledby="pills-pegawai-tab">...</div>
    <div class="tab-pane fade" id="pills-tugas" role="tabpanel" aria-labelledby="pills-tugas-tab" style="padding-top:50px">
        <table class="table" id="tugas-tabel">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Tugas</th>
                    <th scope="col">Pegawai</th>
                    <th scope="col">Tenggat Waktu</th>
                    <th scope="col">Status</th>
                    <th scope="col">Aksi</th>
                </tr>
            </thead>
            <tbody>

                <?php
                $i = 1;
                foreach ($allTugas as $tugas) {
                ?>
                    <tr>
                        <th scope="row"><?php echo $i ?></th>
                        <td><?php echo $tugas->getNama() ?></td>
                        <td><?php foreach ($tugas->getPegawai() as $pegawai) {

                                echo $pegawai->getNama();
                                if ($pegawai != $tugas->getPegawai()[count($tugas->getPegawai()) - 1]) {
                                    echo ", ";
                                }
                            } ?></td>
                        <td><?php echo $tugas->getTenggatWaktu() ?></td>
                        <td><?php echo $tugas->getStatus()['nama'] ?></td>
                        <td>
                            <button type="button" class="btn btn-primary" id="open-modal-tugas-ubah" data-toggle="modal" data-target="#modal-tugas-ubah" data-id="<?php echo $tugas->getId(); ?>" data-tugas="<?php echo $tugas->getNama(); ?>" data-tenggatwaktu="<?php echo $tugas->getTenggatWaktu(); ?>" data-status="<?php echo $tugas->getStatus()['id']; ?>">Ubah Tugas</button>
                            <button type="button" class="btn btn-danger" id="open-modal-tugas-hapus" data-toggle="modal" data-target="#modal-tugas-hapus" data-id="<?php echo $tugas->getId(); ?>">Hapus Tugas</button>
                        </td>

                    </tr>
                <?php
                    $i++;
                }
                ?>

            </tbody>
        </table>

        <div class="row justify-content-center align-items-center">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-tugas-tambah">Tambah Tugas</button>
        </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="modal-tugas-tambah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Tugas</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="tambahTugas" id="form-tambah-tugas" method="POST">
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Tugas</label>
                        <input type="text" class="form-control" name="tugas_nama" aria-describedby="emailHelp" placeholder="Masukan Judul">
                    </div>
                    <!-- <div class="form-group">
                        <label for="exampleFormControlSelect1">Pilih Pegawai</label>
                        <select class="form-control" id="exampleFormControlSelect1">
                        </select>
                    </div> -->
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Tenggat Waktu</label>
                        <input class="input-tenggat-waktu" width="312" name="tugas_tenggat_waktu" placeholder="masukan tanggal" />
                    </div>


                    <button type="submit" class="btn btn-primary" style="margin-top:50px">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-tugas-ubah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ubah Tugas</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="ubahTugas">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Judul Tugas</label>
                        <input type="text" id="tugas-id" name="tugas_id" hidden>

                        <input type="text" class="form-control" id="tugas-nama" name="tugas_nama" aria-describedby="emailHelp" placeholder="Masukan Judul">
                    </div>
                    <!-- <div class="form-group">
                        <label for="exampleFormControlSelect1">Pilih Pegawai</label>
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div> -->
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Tenggat Waktu</label>
                        <input class="input-tenggat-waktu" id="tugas-tenggat-waktu" width="312" name="tugas_tenggat_waktu" placeholder="masukan tanggal" />
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Status Pegerjaan</label>
                        <select class="form-control" id="tugas-status" name="tugas_status">
                            <option value="1">Ditugaskan</option>
                            <option value="2">Selesai</option>
                            <option value="0">Telat</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Ubah</button>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-tugas-hapus" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Hapus Tugas</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="hapusTugas" method="post">
                    <p>Apakah anda yakin ingin menghapus tugas Menyelesaikan Progres FP ?</p>
                    <input type="text" id="tugas-id" name="tugas_id" hidden>
                    <button type="submit" class="btn btn-primary">Iya, Saya yakin</button>
                    <button data-dismiss="modal" class="btn btn-danger">Batalkan</button>
                </form>

            </div>
        </div>
    </div>
</div>

<script>
    $('.input-tenggat-waktu').datetimepicker({
        footer: true,
        modal: true,
        format: 'yyyy-mm-dd HH:MM'
    });

    $(document).on("click", "#open-modal-tugas-hapus", function() {
        var id = $(this).data('id');

        $(".modal-body  #tugas-id").val(id);
    });

    $(document).on("click", "#open-modal-tugas-ubah", function() {
        var id = $(this).data('id');
        var tugas = $(this).data('tugas');
        var tenggatWaktu = $(this).data('tenggatwaktu').slice(0, -3);
        var status = $(this).data('status');

        $(".modal-body  #tugas-id").val(id);
        $(".modal-body  #tugas-nama").val(tugas);
        $(".modal-body  #tugas-tenggat-waktu").val(tenggatWaktu);
        $(".modal-body  #tugas-status").val(status);


    });
</script>