<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="#">MyCo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/index">Keluar</a>
            </li>
        </ul>
    </div>
</nav>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="pills-pegawai-tab" data-toggle="pill" href="#pills-pegawai" role="tab" aria-controls="pills-pegawai" aria-selected="true">Pegawai</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="pills-tugas-tab" data-toggle="pill" href="#pills-tugas" role="tab" aria-controls="pills-tugas" aria-selected="false">Tugas</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="pills-tingkat-tab" data-toggle="pill" href="#pills-tingkat" role="tab" aria-controls="pills-tingkat" aria-selected="false">Tingkat Pegawai</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="pills-absensi-tab" data-toggle="pill" href="#pills-absensi" role="tab" aria-controls="pills-absensi" aria-selected="false">Absensi Pegawai</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="pills-gaji-tab" data-toggle="pill" href="#pills-gaji" role="tab" aria-controls="pills-gaji" aria-selected="false">Gaji Pegawai</a>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-pegawai" role="tabpanel" aria-labelledby="pills-pegawai-tab">...</div>
    <div class="tab-pane fade" id="pills-tugas" role="tabpanel" aria-labelledby="pills-tugas-tab" style="padding-top:50px">
        <table class="table" id="tugas-tabel">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Tugas</th>
                    <th scope="col">Pegawai</th>
                    <th scope="col">Tenggat Waktu</th>
                    <th scope="col">Status</th>
                    <th scope="col">Aksi</th>
                </tr>
            </thead>
            <tbody>

                <?php
                $i = 1;
                foreach ($allTugas as $tugas) {
                ?>
                    <tr>
                        <th scope="row"><?php echo $i ?></th>
                        <td><?php echo $tugas->getNama() ?></td>
                        <td><?php foreach ($tugas->getPegawai() as $pegawai) {

                                echo $pegawai->getNama();
                                if ($pegawai != $tugas->getPegawai()[count($tugas->getPegawai()) - 1]) {
                                    echo ", ";
                                }
                            } ?></td>
                        <td><?php echo $tugas->getTenggatWaktu() ?></td>
                        <td><?php echo $tugas->getStatus()['nama'] ?></td>
                        <td>
                            <button type="button" class="btn btn-primary" id="open-modal-tugas-ubah" data-toggle="modal" data-target="#modal-tugas-ubah" data-id="<?php echo $tugas->getId(); ?>" data-tugas="<?php echo $tugas->getNama(); ?>" data-tenggatwaktu="<?php echo $tugas->getTenggatWaktu(); ?>" data-status="<?php echo $tugas->getStatus()['id']; ?>">Ubah Tugas</button>
                            <button type="button" class="btn btn-danger" id="open-modal-tugas-hapus" data-toggle="modal" data-target="#modal-tugas-hapus" data-id="<?php echo $tugas->getId(); ?>">Hapus Tugas</button>
                        </td>

                    </tr>
                <?php
                    $i++;
                }
                ?>

            </tbody>
        </table>

        <div class="row justify-content-center align-items-center">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-tugas-tambah">Tambah Tugas</button>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-tingkat" role="tabpanel" aria-labelledby="pills-tingkat-tab" style="padding-top:50px">
        <table class="table" id="tingkat-tabel">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Tingkat Pegawai</th>
                    <th scope="col">Jenis Kepegawaian</th>
                    <th scope="col">Golongan</th>
                    <th scope="col">Pendidikan (minimal)</th>
                    <th scope="col">Lama Kerja (minimal)</th>
                    <th scope="col">Gaji Dasar</th>
                    <th scope="col">Aksi</th>
                </tr>
            </thead>
            <tbody>
            <?php
                $i = 1;
                foreach ($allTingkat as $tingkat) {
                ?>
                    <tr>
                    <th scope="row"><?php echo $i ?></th>
                        <td><?php echo $tingkat->getNama() ?></td>
                        <td><?php echo $tingkat->getJenis() ?></td>
                        <td><?php echo $tingkat->getGolongan() ?></td>
                        <td><?php echo $tingkat->getPendidikan() ?></td>
                        <td><?php echo $tingkat->getLamaKerja() ?></td>
                        <td><?php echo "Rp. ".strval($tingkat->getGajiDasar()).".00" ?></td>

                        <td>
                            <button type="button" class="btn btn-primary" id="open-modal-tingkat-ubah" data-toggle="modal" data-target="#modal-tingkat-ubah" data-idtingkat="<?php echo $tingkat->getId(); ?>" data-namatingkat="<?php echo $tingkat->getNama(); ?>" data-jenistingkat="<?php echo $tingkat->getJenis(); ?>" data-golongantingkat="<?php echo $tingkat->getGolongan(); ?>" data-pendidikantingkat="<?php echo $tingkat->getPendidikan(); ?>" data-lamakerjatingkat="<?php echo $tingkat->getLamaKerja(); ?>" data-gajitingkat="<?php echo $tingkat->getGajiDasar(); ?>"> Ubah</button>
                            <button type="button" class="btn btn-danger" id="open-modal-tingkat-hapus" data-toggle="modal" data-target="#modal-tingkat-hapus" data-idtingkat="<?php echo $tingkat->getId(); ?>">Hapus</button>
                        </td>
                     </tr>
                 <?php
                    $i++;
                }
                ?>
            </tbody>
        </table>

        <div class="row justify-content-center align-items-center">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-tingkat-tambah">Tambah Tingkat Pegawai</button>
        </div>
    </div>

    <div class="tab-pane fade" id="pills-absensi" role="tabpanel" aria-labelledby="pills-absensi-tab" style="padding-top:50px">
        <table class="table" id="absensi-tabel">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Tanggal</th>
                    <th scope="col">Nama Pegawai</th>
                    <th scope="col">Absensi Masuk</th>
                    <th scope="col">Absensi Pulang</th>
                </tr>
            </thead>
            <tbody>
            <?php
                $i = 1;
                ?>
                    <tr>
                    <th scope="row"><?php echo $i ?></th>
                        <td><?php  ?></td>
                        <td><?php  ?></td>
                        <td><?php  ?></td>
                        <td><?php  ?></td>
                        <td><?php  ?></td>

                        <td>
                        </td>
                     </tr>
                 <?php
                    $i++;
                ?>
            </tbody>
        </table>

</div>

<div class="tab-pane fade" id="pills-gaji" role="tabpanel" aria-labelledby="pills-gaji-tab" style="padding-top:50px">
        <table class="table" id="gaji-tabel">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Nama Pegawai</th>
                    <th scope="col">Gaji Dasar</th>
                    <th scope="col">Upah Lauk Pauk</th>
                    <th scope="col">Upah Kehadiran</th>
                    <th scope="col">Upah Renumerasi</th>
                    <th scope="col">Total Gaji</th>

                </tr>
            </thead>
            <tbody>
            <?php
                $i = 1;
                ?>
                    <tr>
                    <th scope="row"><?php echo $i ?></th>
                        <td><?php  ?></td>
                        <td><?php  ?></td>
                        <td><?php  ?></td>
                        <td><?php  ?></td>
                        <td><?php  ?></td>

                        <td>
                        </td>
                     </tr>
                 <?php
                    $i++;
                ?>
            </tbody>
        </table>

</div>

<!-- Modal -->
<div class="modal fade" id="modal-tugas-tambah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Tugas</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="tambahTugas" id="form-tambah-tugas" method="POST">
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Tugas</label>
                        <input type="text" class="form-control" name="tugas_nama" aria-describedby="emailHelp" placeholder="Masukan Judul">
                    </div>
                    <!-- <div class="form-group">
                        <label for="exampleFormControlSelect1">Pilih Pegawai</label>
                        <select class="form-control" id="exampleFormControlSelect1">
                        </select>
                    </div> -->
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Tenggat Waktu</label>
                        <input class="input-tenggat-waktu" width="312" name="tugas_tenggat_waktu" placeholder="masukan tanggal" />
                    </div>


                    <button type="submit" class="btn btn-primary" style="margin-top:50px">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-tugas-ubah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ubah Tugas</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="ubahTugas">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Judul Tugas</label>
                        <input type="text" id="tugas-id" name="tugas_id" hidden>

                        <input type="text" class="form-control" id="tugas-nama" name="tugas_nama" aria-describedby="emailHelp" placeholder="Masukan Judul">
                    </div>
                    <!-- <div class="form-group">
                        <label for="exampleFormControlSelect1">Pilih Pegawai</label>
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div> -->
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Tenggat Waktu</label>
                        <input class="input-tenggat-waktu" id="tugas-tenggat-waktu" width="312" name="tugas_tenggat_waktu" placeholder="masukan tanggal" />
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Status Pegerjaan</label>
                        <select class="form-control" id="tugas-status" name="tugas_status">
                            <option value="1">Ditugaskan</option>
                            <option value="2">Selesai</option>
                            <option value="0">Telat</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Ubah</button>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-tugas-hapus" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Hapus Tugas</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="hapusTugas" method="post">
                    <p>Apakah anda yakin ingin menghapus tugas Menyelesaikan Progres FP ?</p>
                    <input type="text" id="tugas-id" name="tugas_id" hidden>
                    <button type="submit" class="btn btn-primary">Iya, Saya yakin</button>
                    <button data-dismiss="modal" class="btn btn-danger">Batalkan</button>
                </form>

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-tingkat-tambah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah Tingkat Pegawai</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="tambahTingkatPegawai" id="form-tambah-tingkat" method="POST">
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Tingkat Pegawai</label>
                        <input type="text" class="form-control" name="tingkat_nama" aria-describedby="emailHelp" placeholder="Masukan Jenis Tingkat Pegawai">
                    </div>
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Jenis Kepegawaian</label>
                        <input type="text" class="form-control" name="tingkat_jenis" aria-describedby="emailHelp" placeholder="Masukan Jenis Kepegawaian">
                    </div>
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Golongan</label>
                        <input type="text" class="form-control" name="tingkat_golongan" aria-describedby="emailHelp" placeholder="Masukan Golongan Kepegawaian">
                    </div>
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Pendidikan (minimal)</label>
                        <input type="text" class="form-control" name="tingkat_pendidikan" aria-describedby="emailHelp" placeholder="Masukan Syarat Pendidikan Minimal">
                    </div>
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Lama Kerja (minimal)</label>
                        <input type="text" class="form-control" name="tingkat_lamakerja" aria-describedby="emailHelp" placeholder="Masukan Syarat Durasi Bekerja Minimal">
                    </div>
                    <div class="form-group" style="margin-bottom:20px">
                        <label for="exampleInputEmail1">Gaji Dasar</label>
                        <input type="text" class="form-control" name="tingkat_gaji" aria-describedby="emailHelp" placeholder="Masukan Gaji Dasar">
                    </div>

                    <button type="submit" class="btn btn-primary" style="margin-top:50px">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-tingkat-ubah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ubah Tingkat Pegawai</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="ubahTingkatPegawai">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tingkat Pegawai</label>
                        <input type="text" id="tingkat-id" name="tingkat_id" hidden>

                        <input type="text" class="form-control" id="tingkat-nama" name="tingkat_nama" aria-describedby="emailHelp" placeholder="Masukan Tingkat Pegawai">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Jenis Kepegawaian</label>
                        <input type="text" class="form-control" id="tingkat-jenis" name="tingkat_jenis" aria-describedby="emailHelp" placeholder="Masukan Jenis Kepegawaian">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Golongan</label>
                        <input type="text" class="form-control" id="tingkat-golongan" name="tingkat_golongan" aria-describedby="emailHelp" placeholder="Masukan Golongan Kepegawaian">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Pendidikan (minimal)</label>
                        <input type="text" class="form-control" id="tingkat-pendidikan" name="tingkat_pendidikan" aria-describedby="emailHelp" placeholder="Masukan Syarat Pendidikan Minimal">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Lama Kerja (minimal)</label>
                        <input type="text" class="form-control" id="tingkat-lamakerja" name="tingkat_lamakerja" aria-describedby="emailHelp" placeholder="Masukan Syarat Lama Kerja Minimal">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Gaji Dasar</label>
                        <input type="text" class="form-control" id="tingkat-gaji" name="tingkat_gaji" aria-describedby="emailHelp" placeholder="Masukan Gaji Dasar">
                    </div>
                    <button type="submit" class="btn btn-primary">Ubah</button>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-tingkat-hapus" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Hapus Tingkat Pegawai</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="hapusTingkatPegawai" method="post">
                    <p>Apakah anda yakin ingin menghapus tingkat pegawai ini ?</p>
                    <input type="text" id="tingkat-id" name="tingkat_id" hidden>
                    <button type="submit" class="btn btn-primary">Iya, Saya yakin</button>
                    <button data-dismiss="modal" class="btn btn-danger">Batalkan</button>
                </form>

            </div>
        </div>
    </div>
</div>

<script>
    $('.input-tenggat-waktu').datetimepicker({
        footer: true,
        modal: true,
        format: 'yyyy-mm-dd HH:MM'
    });

    $(document).on("click", "#open-modal-tugas-hapus", function() {
        var id = $(this).data('id');

        $(".modal-body  #tugas-id").val(id);
    });

    $(document).on("click", "#open-modal-tugas-ubah", function() {
        var id = $(this).data('id');
        var tugas = $(this).data('tugas');
        var tenggatWaktu = $(this).data('tenggatwaktu').slice(0, -3);
        var status = $(this).data('status');

        $(".modal-body  #tugas-id").val(id);
        $(".modal-body  #tugas-nama").val(tugas);
        $(".modal-body  #tugas-tenggat-waktu").val(tenggatWaktu);
        $(".modal-body  #tugas-status").val(status);

    });

    $(document).on("click", "#open-modal-tingkat-hapus", function() {
        var id = $(this).data('idtingkat');

        $(".modal-body  #tingkat-id").val(id);
    });

   $(document).on("click", "#open-modal-tingkat-ubah", function() {
        var id = $(this).data('idtingkat');
        var nama = $(this).data('namatingkat');
        var jenis = $(this).data('jenistingkat');
        var golongan = $(this).data('golongantingkat');
        var pendidikan = $(this).data('pendidikantingkat');
        var lamakerja = $(this).data('lamakerjatingkat');
        var gaji_dasar = $(this).data('gajitingkat');

        $(".modal-body  #tingkat-id").val(id);
        $(".modal-body  #tingkat-nama").val(nama);
        $(".modal-body  #tingkat-jenis").val(jenis);
        $(".modal-body  #tingkat-golongan").val(golongan);
        $(".modal-body  #tingkat-pendidikan").val(pendidikan);
        $(".modal-body  #tingkat-lamakerja").val(lamakerja);
        $(".modal-body  #tingkat-gaji").val(gaji_dasar);
    });
</script>